# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    servo_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


servo_controller:
  ros__parameters:
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - hombro
      - codo
      - muneca
      - articulacion

joint_state_broadcaster:
  ros__parameters:
    joints:
      - hombro
      - codo
      - muneca
      - articulacion

